<hr>
<h1>Đăng nhập thành viên</h1>
<br>

<div id="login">
	<form action="<?= domain ?>user/select" method="post">
    <ul class="login">
    	<li><label for="login">User</label></li>
    	<li><input type="text" id="login" name="login" size="30" /></li>
    	<li><label for="password">Password</label></li>
    	<li><input type="password" id="password" name="password" size="30" /></li>
    	<li></li>
    	<li><button>Login</button></li>
    </ul>
    </form>
</div>

<form action="<?= domain ?>user/register" method="post">
<!-- Begin Box -->
<div class="box">
    <div class="box_01">
        <div class="box_01_1"><h1>ĐĂNG KÝ THÀNH VIÊN</h1></div>
        <div class="box_01_2"></div>
    </div>
    <div class="box_02">
        <div id="user">
            <ul class="user top">
                <li><div>Tên truy cập</div></li>
                <li><div>Mật khẩu</div></li>
                <li><div>Nhập lại mật khẩu</div></li>
                <li><div>X</div></li>

            </ul>
            <ul class="user bottom even">
                <li><div><input type="text" name="login" /></div></li>
                <li><div><input type="text" name="password" /></div></li>
                <li><div><input type="text" name="repeatPassword" /></div></li>
                <li><div><button>Thêm thành viên</button></div></li>
            </ul>
        </div>     
    </div>
    <div class="box_03"></div>
</div>
<!-- End Box -->
</form>
