<!-- Begin Box -->
<div class="box">
    <div class="box_01">
        <div class="box_01_1"><h1>DANH SÁCH THÀNH VIÊN VÀO TIỀN</h1></div>
        <div class="box_01_2">
        	<?php $this->partial("datetime", array('action' => 'import'))?>
        </div>
    </div>
    <div class="box_02">
		<div id="import">
		    <ul class="import top">
		    	<li><div>STT</div></li>
		    	<li><div style="width:120px">Ngày giờ</div></li>
		    	<li><div style="width:100px; text-align: left">Thành viên</div></li>
		    	<li style="width:100%; min-width: 80px; text-align: left">Lý do ra </li>
		    	<li><div>500.000</div></li>
		    	<li><div>200.000</div></li>
		    	<li><div>100.000</div></li>
		    	<li><div>50.000</div></li>
		    	<li><div>20.000</div></li>
		    	<li><div>10.000</div></li>
		    	<li><div>5.000</div></li>
		    	<li><div>2.000</div></li>
		    	<li><div>1.000</div></li>
		    	<li><div>Số tờ</div></li>
		    	<li><div style="width:100px">Tổng số tiền</div></li>
		    	<li><div>Sửa</div></li>
		    	<li><div>Xoá</div></li>
		    </ul>
		    <?php foreach ($Import as $ki => $i) : ?>
		    <ul class="import bottom <?php echo ($ki%2) ? 'odd' : 'even' ?>  bg<?= $i->id ?>">
		    	<li><div><?= $ki+1 ?></div></li>
		    	<li><div style="width:120px"><?= $i->datetime ?><div></li>
		    	<li><div style="width:100px; text-align: left"><?= $i->user ?></div></li>
		    	<li style="width:100%; min-width: 80px; text-align: left"><?= $i->import ?></li>
		    	<li><div><?= $i->l500000 ?></div></li>
		    	<li><div><?= $i->l200000 ?></div></li>
		    	<li><div><?= $i->l100000 ?></div></li>
		    	<li><div><?= $i->l50000 ?></div></li>
		    	<li><div><?= $i->l20000 ?></div></li>
		    	<li><div><?= $i->l10000 ?></div></li>
		    	<li><div><?= $i->l5000 ?></div></li>
		    	<li><div><?= $i->l2000 ?></div></li>
		    	<li><div><?= $i->l1000 ?></div></li>
		    	<li><div>1</div></li>
		    	<li><div style="width:100px"><?= number_format($i->totals) ?></div></li>
		    	<li><div><a href="<?= domain ?>import/edit/<?= $i->id ?>">Sửa</a></div></li>
		    	<li><div><a href="<?= domain ?>import/delete/<?= $i->id ?>" class="delete">Xoá</a></div></li>
		    </ul>
		    <?php
		    	$i500000 += $i->l500000;
		    	$i200000 += $i->l200000;
		    	$i100000 += $i->l100000;
		    	$i50000 += $i->l50000;
		    	$i20000 += $i->l20000;
		    	$i10000 += $i->l10000;
		    	$i5000 += $i->l5000;
		    	$i2000 += $i->l2000;
		    	$i1000 += $i->l1000;
		    	$importTotals += $i->totals;
		    ?>
		    <?php endforeach ?>
		    <ul class="import bottom" style="background: #f8f8f8; border-top: #d9d9d9 solid 1px;">
		    	<li style="width:100%; text-align: right"><b>Tổng số</b></li>
		    	<li><div><?= $i500000 ?></div></li>
		    	<li><div><?= $i200000 ?></div></li>
		    	<li><div><?= $i100000 ?></div></li>
		    	<li><div><?= $i50000 ?></div></li>
		    	<li><div><?= $i20000 ?></div></li>
		    	<li><div><?= $i10000 ?></div></li>
		    	<li><div><?= $i5000 ?></div></li>
		    	<li><div><?= $i2000 ?></div></li>
		    	<li><div><?= $i1000 ?></div></li>
		    	<li><div style="width:298px"><strong><?= number_format($importTotals) ?></strong><sup>vnd</sup></div></li>
		    </ul>
		</div>    
    </div>
    <div class="box_03"></div>
</div>
<!-- End Box -->