<!-- Begin Box -->
<div class="box">
    <div class="box_01">
    	<div class="box_01_1"><h1>THỐNG KÊ</h1></div>
        <div class="box_01_2"></div>
    </div>
    <div class="box_02">
		<div id="statistics">
		    <ul class="statistics top">
		    	<li style="width:100%; text-align: left">Tổng số tiền trong két</li>
		    	<li><div>500.000</div></li>
		    	<li><div>200.000</div></li>
		    	<li><div>100.000</div></li>
		    	<li><div>50.000</div></li>
		    	<li><div>20.000</div></li>
		    	<li><div>10.000</div></li>
		    	<li><div>5.000</div></li>
		    	<li><div>2.000</div></li>
		    	<li><div>1.000</div></li>
		    	<li><div>Số tờ</div></li>
		    </ul>
		    <ul class="statistics bottom even">
		    	<li style="width:100%; text-align: left"><?= number_format($stotals) ?></li>
		    	<li><div id="<?= $s500000 ?>" class="s500000"><?= $s500000 ?></div></li>
		    	<li><div id="<?= $s200000 ?>" class="s200000"><?= $s200000 ?></div></li>
		    	<li><div id="<?= $s100000 ?>" class="s100000"><?= $s100000 ?></div></li>
		    	<li><div id="<?= $s50000 ?>" class="s50000"><?= $s50000 ?></div></li>
		    	<li><div id="<?= $s20000 ?>" class="s20000"><?= $s20000 ?></div></li>
		    	<li><div id="<?= $s10000 ?>" class="s10000"><?= $s10000 ?></div></li>
		    	<li><div id="<?= $s5000 ?>" class="s5000"><?= $s5000 ?></div></li>
		    	<li><div id="<?= $s2000 ?>" class="s2000"><?= $s2000 ?></div></li>
		    	<li><div id="<?= $s1000 ?>" class="s1000"><?= $s1000 ?></div></li>
		    	<li><div><?= $s500000 + $s200000 + $s100000 + $s50000 + $s20000 + $s10000 + $s5000 + $s2000 + $s100 ?></div></li>
		    </ul>
		</div>	 
    </div>
    <div class="box_03"></div>
</div>
<!-- End Box -->
