<!-- Begin Box -->
<div class="box">
    <div class="box_01">
        <div class="box_01_1"><h1>DANH SÁCH RA TIỀN</h1></div>
        <div class="box_01_2">
        	<?php $this->partial("datetime", array('action' => 'export'))?>
        </div>
    </div>
    <div class="box_02">
		<div id="export">
		    <ul class="export top">
		    	<li><div>STT</div></li>
		    	<li><div style="width:120px">Ngày giờ</div></li>
		    	<li><div style="width:100px; text-align: left">Thành viên</div></li>
		    	<li style="width:100%; min-width: 80px; text-align: left">Lý do ra </li>
		    	<li><div>500.000</div></li>
		    	<li><div>200.000</div></li>
		    	<li><div>100.000</div></li>
		    	<li><div>50.000</div></li>
		    	<li><div>20.000</div></li>
		    	<li><div>10.000</div></li>
		    	<li><div>5.000</div></li>
		    	<li><div>2.000</div></li>
		    	<li><div>1.000</div></li>
		    	<li><div>Số tờ</div></li>
		    	<li><div style="width:100px">Tổng số tiền</div></li>
		    	<li><div>Sửa</div></li>
		    	<li><div>Xoá</div></li>
		    </ul>
		    <?php foreach ($Export as $ke => $e) : ?>
		    <ul class="export bottom <?php echo ($ke%2) ? 'odd' : 'even' ?>  bg<?= $e->id ?>">
		    	<li><div><?= $ke+1 ?></div></li>
		    	<li><div style="width:120px"><?= $e->datetime ?><div></li>
		    	<li><div style="width:100px; text-align: left"><?= $e->user ?></div></li>
		    	<li style="width:100%; min-width: 80px; text-align: left"><?= $e->export ?></li>
		    	<li><div><?= $e->l500000 ?></div></li>
		    	<li><div><?= $e->l200000 ?></div></li>
		    	<li><div><?= $e->l100000 ?></div></li>
		    	<li><div><?= $e->l50000 ?></div></li>
		    	<li><div><?= $e->l20000 ?></div></li>
		    	<li><div><?= $e->l10000 ?></div></li>
		    	<li><div><?= $e->l5000 ?></div></li>
		    	<li><div><?= $e->l2000 ?></div></li>
		    	<li><div><?= $e->l1000 ?></div></li>
		    	<li><div>1</div></li>
		    	<li><div style="width:100px"><?= number_format($e->totals) ?></div></li>
		    	<li><div><a href="<?= domain ?>export/edit/<?= $e->id ?>">Sửa</a></div></li>
		    	<li><div><a href="<?= domain ?>export/delete/<?= $e->id ?>" class="delete">Xoá</a></div></li>
		    </ul>
		    <?php
		    	$e500000 += $e->l500000;
		    	$e200000 += $e->l200000;
		    	$e100000 += $e->l100000;
		    	$e50000 += $e->l50000;
		    	$e20000 += $e->l20000;
		    	$e10000 += $e->l10000;
		    	$e5000 += $e->l5000;
		    	$e2000 += $e->l2000;
		    	$e1000 += $e->l1000;
		    	$exportTotals += $e->totals;
		    ?>
		    <?php endforeach ?>
		    <ul class="export bottom" style="background: #f8f8f8; border-top: #d9d9d9 solid 1px;">
		    	<li style="width:100%; text-align: right"><b>Tổng số</b></li>
		    	<li><div><?= $e500000 ?></div></li>
		    	<li><div><?= $e200000 ?></div></li>
		    	<li><div><?= $e100000 ?></div></li>
		    	<li><div><?= $e50000 ?></div></li>
		    	<li><div><?= $e20000 ?></div></li>
		    	<li><div><?= $e10000 ?></div></li>
		    	<li><div><?= $e5000 ?></div></li>
		    	<li><div><?= $e2000 ?></div></li>
		    	<li><div><?= $e1000 ?></div></li>
		    	<li><div style="width:298px"><strong><?= number_format($exportTotals) ?></strong><sup>vnd</sup></div></li>
		    </ul>
		</div>    
    </div>
    <div class="box_03"></div>
</div>
<!-- End Box -->