<form action="<?=domain ?>export/<?= actionForm ?>" method="post" id="postExport">
<input type="hidden" name="id" value="<?= $id ?>" />
<!-- Begin Box -->
<div class="box">
    <div class="box_01">
        <div class="box_01_1"><h1>RA TIỀN</h1></div>
        <div class="box_01_2"><?php echo ($stotals) ? 'Dùng phím tab để di chuyển' : 'Trong két đã hết tiền không thể ra tiền vào lúc này' ?></div>
    </div>
    <div class="box_02">
        <div id="export">
            <ul class="export top">
                <li style="width:100%; text-align: left">Lý do ra tiền</li>
                <li><div>500.000</div></li>
                <li><div>200.000</div></li>
                <li><div>100.000</div></li>
                <li><div>50.000</div></li>
                <li><div>20.000</div></li>
                <li><div>10.000</div></li>
                <li><div>5.000</div></li>
                <li><div>2.000</div></li>
                <li><div>1.000</div></li>
                <li><div style="width:100px">Tổng số tiền</div></li>
                <li><div style="width:80px">X</div></li>
            </ul>
            <ul class="export bottom even">
                <li style="width:100%; text-align: left"><input id="inputExport" type="text" name="export" style="width:99%" value="<?= $export ?>" /></li>
                <li><div><input type="text" id="500000" name="l500000" value="<?= $l500000 ?>" /></div></li>
                <li><div><input type="text" id="200000" name="l200000" value="<?= $l200000 ?>" /></div></li>
                <li><div><input type="text" id="100000" name="l100000" value="<?= $l100000 ?>" /></div></li>
                <li><div><input type="text" id="50000" name="l50000" value="<?= $l50000 ?>" /></div></li>
                <li><div><input type="text" id="20000" name="l20000" value="<?= $l20000 ?>" /></div></li>
                <li><div><input type="text" id="10000" name="l10000" value="<?= $l10000 ?>" /></div></li>
                <li><div><input type="text" id="5000" name="l5000" value="<?= $l5000 ?>" /></div></li>
                <li><div><input type="text" id="2000" name="l2000" value="<?= $l2000 ?>" /></div></li>
                <li><div><input type="text" id="1000" name="l1000" value="<?= $l1000 ?>" /></div></li>
                <li><div style="width:100px; font-weight:bold" class="exportTotals"><?= number_format($totals) ?></div></li>
                <li><div style="width:80px"><button>Ra tiền</button></div></li>
            </ul>
        </div>     
    </div>
    <div class="box_03"></div>
</div>
<!-- End Box -->
</form>