<hr>
<h1>Đăng nhập thành viên</h1>
<br>

<div id="login">
	<form action="<?= domain ?>user/select" method="post">
    <ul class="login">
    	<li><label for="login">User</label></li>
    	<li><input type="text" id="login" name="login" size="30" /></li>
    	<li><label for="password">Password</label></li>
    	<li><input type="password" id="password" name="password" size="30" /></li>
    	<li></li>
    	<li><button>Login</button></li>
    </ul>
    </form>
</div>