<?php $this->view->setVar('Auth', $this->session->get('auth')); ?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Safe</title>
<link type="text/css" rel="stylesheet" href="<?= domain ?>assets/css/stylesheet.css?<?php echo rand(1,233)?>" />
<link type="text/css" rel="stylesheet" href="<?= domain ?>assets/css/css.css?<?php echo rand(1,233)?>" />
<script type="text/javascript" src="<?= domain ?>assets/js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="<?= domain ?>assets/js/jquery-1.11.0.min.map"></script>
<script type="text/javascript" src="<?= domain ?>assets/js/jquery.number.min.js"></script>

<script type="text/javascript">
$( document ).ready(function() {
    $(".delete").on("click", null, function(){
            return confirm("Bạn muốn xoá dữ liệu này?");
    }); 

    $('#postExport').keyup(function() {
        var sum = 0;
        $.each($('#postExport input'),function(){
            var par = Number($(this).attr('id'));
            var value = Number($(this).val());
            if(!isNaN(par) && !isNaN(value)) sum += parseFloat(value * par); 
        });

        $('.exportTotals').html(sum).number(true,0);    
    }); 

    $('#postImport').keyup(function() {
        var sum = 0;
        $.each($('#postImport input'),function(){
            //alert(par);
            var par = Number($(this).attr('id'));
            var value = Number($(this).val());
            if(!isNaN(par) && !isNaN(value)) sum += parseFloat(value * par); 
        });

        $('.importTotals').html(sum).number(true,0);    
    }); 

    $('.export input').keyup(function() {
       var par = Number($(this).attr('id'));
       var value = Number($(this).val());
       var statistics = $('.statistics').find('.s'+par).attr('id');   
       var html = statistics - value; 
       $('.s'+par).html(html);    
    }); 

    $('.import input').keyup(function() {
       var par = Number($(this).attr('id'));
       var value = Number($(this).val());
       var statistics = $('.statistics').find('.s'+par).attr('id');   
       var html = Number(statistics) + Number(value); 
       $('.s'+par).html(html);    
    }); 

    $('#postExport').submit(function() {
        var inputExport = $('#inputExport').val();
        if(inputExport=='') {
            alert('Ê Ku ! Lý do ra tiền là gì vậy?');
            return false;
        }    
    });

    $('#postImport').submit(function() {
        var inputImport = $('#inputImport').val();
        if(inputImport=='') {
            alert('Ê Ku ! Lý do vào tiền là gì vậy?');
            return false;
        }    
    });

    // $('.delete').click(function() {
    //     var id = $(this).attr('id');
    //     var rel = $(this).attr('rel');
    //     $.get(rel, { id: id },function(data){
    //         alert("Data Loaded: " + data);
    //     });
    //     $(this).closest("ul").fadeOut(500);
    //     return false;
    // });

    <?php if($Type != 1) { ?>
    $(window).scroll(function(){
      if ($(window).scrollTop() >= 300) $('.top').addClass('fixed');
      else $('.top').removeClass('fixed');
    });
    <?php } ?>

    <?php if($stotals==0) { ?>
        $('.export').find('input').prop('disabled', true);
    <?php } ?>

    <?php if($id) { ?>
    $('.bg<?php echo $id ?>').css({'background-color': '#DDDDDD', 'font-weight': 'bolder'});
    <?php } ?>

});
</script>

</head>

<body>
<div id="container">
    <div class="container">
        
        <header>
            <div id="header">
                <div class="header">
                    <!-- Header -->
                    <?php $this->partial("header") ?>
                </div>    
            </div>
        </header>
        <nav>
            <div id="navigation">
                <div class="navigation">
                    <!-- Navigation -->
                    <?php //$this->partial("navigation") ?>
                </div>
            </div>
        </nav>
        <section>
            <div id="content">
                <div class="content">
                    <!-- Content -->
                <?php echo $this->getContent() ?> 
                </div>
            </div> 
        </section>    
        <footer>
            <div id="footer">
                <div class="footer">
                    <!-- Footer -->
                    <?php //$this->partial("footer") ?>
                </div>    
            </div> 
        </footer>
        
    </div>
</div>    
</body>
</html>